### ISSUE TITLE
Compatible with base-4.9?

### ISSUE THREAD

**Issue by sburke-at-ziprecruiter** [basvandijk/threads#12] opened 2016-06-09 19:21 UTC
The dependency base (>=4.4 && <4.9)  prevents building projects from the latest base-4.9.

**Comment by hvr** [comment] 2016-06-10 08:12
duplicate of #11

**Comment by basvandijk** [comment] 2016-06-10 09:51
I released 0.5.1.4 which is compatible with base-4.9

**Closed by basvandijk** 2016-06-10 09:51 UTC

**Comment by hvr** [comment] 2016-06-11 15:32
@basvandijk thx!
